### ISSUE TITLE
running script bin/console ngscheduledvisibility:update without human interaction as cronjob

### ISSUE THREAD

**Issue by fwoldt** [netgen/ibexa-scheduled-visibility#2]
How can the script 

bin/console ngscheduledvisibility:update

be run as a cronjob?

The script asking to type yes to continue.

![grafik](https://github.com/netgen/ibexa-scheduled-visibility/assets/417608/f309da42-bed0-4312-9365-3ed40741b5a2)

I think we need an option to force execution, so no useraction is required.

**Comment by emodric** [comment]
@fwoldt You can use `--no-interaction` switch provided by Symfony Console.

**Comment by fwoldt** [comment]
thank's  it is working
