### ISSUE TITLE
Exception running cronjob ngscheduledvisibility:update 

### ISSUE THREAD

**Issue by fwoldt** [netgen/ibexa-scheduled-visibility#6]
We get the following Error while running cronjob on one of our testsystems:

`php bin/console ngscheduledvisibility:update --no-interaction`

 ```
 Netgen\Bundle\IbexaScheduledVisibilityBundle\Command\ScheduledVisibilityUpdateCommand::loadLanguage(): Argument #1 ($id) must be of type int, string given,   
  called in /.../vendor/netgen/ibexa-scheduled-visibility/bundle/Command/ScheduledVisibilityUpdateCommand.php on line 150 

```
![grafik](https://github.com/user-attachments/assets/9651ec47-ab91-4cfe-a55d-338581ab2eb4)

**Comment by emodric** [comment]
@fwoldt Fixed in 1.0.2!

Thanks for the report!
